// src/Components/Contacto.jsx
import React from "react";
import '../Stylesheets/Contacto.sass';

function Contacto() {
    const copyText = (event) => {
        const text = event.currentTarget.querySelector("p").textContent;
        navigator.clipboard.writeText(text)
        .then(alert("Copiado al portapapeles!"))  
        .catch(err => console.log("Error: ", err));      
    };

    return (
        <div className="container" id="contacto">
            <h2>Contacto</h2>
            <div className="contain" onClick={copyText} style={{ cursor: "pointer" }}>
                <div className="hover">
                    <i className="fa-regular fa-envelope"></i>
                    <p>FacundoIvanBritez@gmail.com</p>
                </div>
                <span>Click to copy!</span>
            </div>
            <div className="contain" onClick={copyText} style={{ cursor: "pointer" }}>
                <div className="hover">
                    <i className="fa-brands fa-whatsapp"></i>
                    <p>+54 11 6948 7170</p>
                </div>
                <span>Click to copy!</span>
            </div>
        </div>
    );
}

export default Contacto;

// src/app/components/contacto/contacto.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-contacto',
  templateUrl: './contacto.component.html',
  styleUrls: ['./contacto.component.sass']
})
export class ContactoComponent {
  copyContent() {
    const emailElement = document.getElementById('mail') as HTMLParagraphElement;
    const email = emailElement.innerText;
    navigator.clipboard.writeText(email).then(() => {
      console.log('Contenido copiado al portapapeles');
    }).catch((error) => {
      console.error('Error al copiar contenido al portapapeles:', error);
    });
  }
}

<div class="container">
    <h2>Contacto</h2>
    <p id="mail">FacundoIvanBritez@gmail.com</p>
    <button class="" (click)="copyContent()">Copy!</button>
</div>
